# Generated by Django 2.0.6 on 2018-07-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_alimento', models.CharField(help_text='Tipo de alimento', max_length=100)),
                ('Precio', models.CharField(help_text='Precio del alimento', max_length=120)),
                ('Cantidad', models.CharField(help_text='Cantidad de alimento', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_animal', models.CharField(help_text='Tipo de animal', max_length=50)),
                ('Edad', models.CharField(help_text='Edad del animal', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_del_empleado', models.CharField(help_text='Nombre del empleado', max_length=60)),
                ('Cargo', models.CharField(help_text='Cargo del empleado', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_de_Vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_de_la_vacuna', models.CharField(help_text='Nombre de la vacuna', max_length=100)),
                ('Cantidad', models.CharField(help_text='Cantidad del producto', max_length=120)),
                ('Fecha_de_aplicacion', models.DateField(help_text='Fecha de aplicacion de la vacuna')),
                ('Dosis', models.CharField(help_text='Dosis de la vacuna', max_length=50)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.Animales')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_vacuna', models.CharField(help_text='Nombre de la vacuna', max_length=50)),
                ('Fecha_de_vencimiento', models.DateField(help_text='Fecha de vencimiento de la vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre', max_length=60)),
                ('Apellido', models.CharField(help_text='Apellido', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='animales',
            name='Vacunas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.Vacunas'),
        ),
    ]
